version: "3.9"
services:
  lab:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes: 
      - .:/app
    stdin_open: true
    tty: true

  jenkins:
    image: jenkinsci/blueocean
    environment: 
      - DOCKER_HOST=tcp://host.docker.internal.2375
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home